### dtype 

The numpy.dtype class in NumPy represents the data type of elements in a NumPy array. It defines:

The type of data (e.g., integer, float, string, etc.)
The size in bytes (e.g., int32 vs int64)
Whether the data is byte-swapped (endianness)
For structured arrays, the field names and types

Essentially, dtype is the backbone of how NumPy handles data efficiently.

#### Structured arrays 

Structured arrays in NumPy allow you to store heterogeneous data (different types in one array), similar to a table or a record in a database. Each element of the array can have multiple fields, each with its own data type.
This is useful for:

Representing tabular data (like rows in a CSV)
Handling complex datasets without using pandas

Structured arrays are defined using dtype with a list of tuples specifying field names and types.

In [2]:
import numpy as np 
data = [(1, 1**0.5), (2, 2**0.5), (3, 3**0.5)]
arr_1 = np.array(data, dtype=[('x', int), ('root_x',float)])

arr_1

array([(1, 1.        ), (2, 1.41421356), (3, 1.73205081)],
      dtype=[('x', '<i8'), ('root_x', '<f8')])

In [3]:
# this is still a 1-D array
arr_1.ndim

1

In [4]:
# you can access columns in data
arr_1['x']

array([1, 2, 3])

In [5]:
arr_1['root_x']

array([1.        , 1.41421356, 1.73205081])

In [3]:
arr_2d = np.zeros((2, 3), dtype=[('x', int), ('root_x', float)])

# Fill it (example: x = i*10 + j)
for i in range(arr_2d.shape[0]):
    for j in range(arr_2d.shape[1]):
        x_val = i * 10 + j
        arr_2d[i, j]['x'] = x_val
        arr_2d[i, j]['root_x'] = np.sqrt(x_val)

arr_2d

array([[( 0, 0.        ), ( 1, 1.        ), ( 2, 1.41421356)],
       [(10, 3.16227766), (11, 3.31662479), (12, 3.46410162)]],
      dtype=[('x', '<i8'), ('root_x', '<f8')])

In [4]:
print(arr_2d.shape)     # (2, 3)
print(arr_2d['x'])      # 2D array of ints
print(arr_2d['root_x']) # 2D array of float

(2, 3)
[[ 0  1  2]
 [10 11 12]]
[[0.         1.         1.41421356]
 [3.16227766 3.31662479 3.46410162]]


#### Adding size for arrays inside fields
You can store arrays inside a single field:

In [ ]:
dtype_with_array = np.dtype([
    ('name', 'U10'),
    ('scores', 'f4', (3,))  # 3 floats per record
])

data = np.array([
    ('Alice', [85.5, 90.0, 88.0]),
    ('Bob', [78.0, 82.5, 80.0])
], dtype=dtype_with_array)

print(data)
# [('Alice', [85.5, 90., 88.]) ('Bob', [78., 82.5, 80.])]
print(data['scores'])
# [[85.5 90.  88. ]
#  [78.  82.5 80. ]]


array([[(0, [0., 0., 0.]), (0, [0., 0., 0.])],
       [(0, [0., 0., 0.]), (0, [0., 0., 0.])]],
      dtype=[('x', '<i8'), ('vec', '<f8', (3,))])

#### Nested structured dtype
You can nest structures inside fields:

In [6]:

nested_dtype = np.dtype([
    ('name', 'U10'),
    ('details', [('age', 'i4'), ('marks', 'f4')])
])

nested_data = np.array([
    ('Alice', (25, 85.5)),
    ('Bob', (30, 90.0))
], dtype=nested_dtype)

print(nested_data)
# [('Alice', (25, 85.5)) ('Bob', (30, 90.))]
print(nested_data['details']['marks'])  # [85.5 90.]

[('Alice', (25, 85.5)) ('Bob', (30, 90. ))]
[85.5 90. ]
