In [ ]:
# DAV:
# DAV1: PYTHON Libraries
# DAV2: Prob & Stats
# DAV3: Hypothesis Testing

# DAV1:
# NUMPY
# PANDAS
# MATPLOTLIB
# SEABORN

# https://colab.research.google.com/drive/1Syh4UzZb78kV7kEQ8S_lvDAVc16XUOs0?usp=sharing

In [ ]:
# Python Lists vs Numpy Array
# Why use Numpy over Python lists?
# Shape & Dimension
# numpy.arange # Please note the spelling for arange
# Typecasting & Dtypes

### Numpy arrays are faster

it takes 1.7 micro seconds to create a python array of squares:

In [ ]:
a = [1, 2, 3, 4, 5]
%timeit [i**2 for i in a]

1.7 µs ± 226 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


But it takes 622 nano seconds for the same in numpy:

In [ ]:
import numpy as np
n = np.array(a)
%timeit n ** 2 #Broadcasting operation

622 ns ± 27.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Shape
Shape describes Number of elements across each dimension

In [ ]:
np.shape(n) # 

(5,)

### Dimension
Describes number of levels of array or axes of an array

In [ ]:
np.ndim(n)

1

In [ ]:
np.arange(1,5,1)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### Numpy arrays are homogeneous 

In [ ]:
x = np.array([1, 2.3, 'test'])

In [ ]:
x

array(['1', '2.3', 'test'], dtype='<U32')

In [ ]:
np.array(['Saptarshi', 'abc'], dtype='float') # String > Float > Int

ValueError: ignored

In [ ]:
n

array([1, 2, 3, 4, 5])

In [ ]:
n1 = n.astype('float64')

In [ ]:
n1

array([1., 2., 3., 4., 5.])

In [ ]:
x = np.array(['abc', 1.2])

In [ ]:
x

array(['abc', '1.2'], dtype='<U32')

### Indexing
Indexing in np arrays, works same as python lists

In [ ]:
m1 = np.arange(12)

In [ ]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[0]

0

In [ ]:
m1[6]

6

In [ ]:
m1[-1]

11

In [ ]:
m1[-1:-4:-1]

array([11, 10,  9])

In [ ]:
m1[[2,3,5,7]]

array([2, 3, 5, 7])

In [ ]:
m1[2,3,5,7]

IndexError: ignored

In [ ]:
import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1 < 6

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [ ]:
m1 [m1 < 6] # Numpy array filtering operation

array([0, 1, 2, 3, 4, 5])

In [ ]:
m1[ m1 %2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
str(m1)

'[ 0  1  2  3  4  5  6  7  8  9 10 11]'

In [ ]:
a = np.array([1,2,3,4,5])

b = np.array([8,7,6])

a[3:] = b[::-2]

In [ ]:
a

array([1, 2, 3, 6, 8])

In [ ]:
a[3:]

array([4, 5])

In [ ]:
b[::-2]

array([6, 8])