## Broadcasting

Broadcasting in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes without explicitly copying data.
Instead of creating large intermediate arrays, NumPy stretches smaller arrays across larger ones so that element-wise operations can happen efficiently.

### Key Rules of Broadcasting
When operating on two arrays:


Compare their shapes from the trailing dimensions backward; <br>Dimensions are compatible if:
1. They are equal, OR
2. One of them is 1

If a dimension is 1, NumPy broadcasts (repeats) that dimension to match the other.

In [7]:
import numpy as np 

A = np.random.randint(low=-10, high=10, size=(3, 4, 5))
A

array([[[ -9,   2, -10,   7,   1],
        [  4,   5,   0,   6,  -1],
        [-10, -10,   6, -10,  -9],
        [  0,  -8,   1,   5,   6]],

       [[ -5,   9,  -6,   6,   2],
        [  7,   1,  -9,  -2, -10],
        [  6,  -5,  -9,  -1, -10],
        [ -7, -10,   3,   2,  -7]],

       [[ -5,  -4,  -9,   1,   9],
        [  8,   0,   6,   8,  -8],
        [ -9,  -9,  -7,   3,   2],
        [  7, -10,   9,   3,  -2]]], dtype=int32)

In [10]:
B = np.random.randint(low=-10, high=10, size=(3, 1, 5))
B

array([[[  4,  -7,  -9,  -8,   5]],

       [[ -5, -10,   8,  -2,   4]],

       [[ -7,  -4,  -6, -10,   5]]], dtype=int32)

In [11]:
A + B

array([[[ -5,  -5, -19,  -1,   6],
        [  8,  -2,  -9,  -2,   4],
        [ -6, -17,  -3, -18,  -4],
        [  4, -15,  -8,  -3,  11]],

       [[-10,  -1,   2,   4,   6],
        [  2,  -9,  -1,  -4,  -6],
        [  1, -15,  -1,  -3,  -6],
        [-12, -20,  11,   0,  -3]],

       [[-12,  -8, -15,  -9,  14],
        [  1,  -4,   0,  -2,  -3],
        [-16, -13, -13,  -7,   7],
        [  0, -14,   3,  -7,   3]]], dtype=int32)

### Explanation
B has been tiled across 2nd dimension first <br>
B's dimension is (3, 1, 5), after tiling it by repeating axes by (1, 4, 1) times, it becomes (3, 4, 5)

In [14]:
B_tiled = np.tile(B, reps=(1, 4, 1)) # 
B_tiled

array([[[  4,  -7,  -9,  -8,   5],
        [  4,  -7,  -9,  -8,   5],
        [  4,  -7,  -9,  -8,   5],
        [  4,  -7,  -9,  -8,   5]],

       [[ -5, -10,   8,  -2,   4],
        [ -5, -10,   8,  -2,   4],
        [ -5, -10,   8,  -2,   4],
        [ -5, -10,   8,  -2,   4]],

       [[ -7,  -4,  -6, -10,   5],
        [ -7,  -4,  -6, -10,   5],
        [ -7,  -4,  -6, -10,   5],
        [ -7,  -4,  -6, -10,   5]]], dtype=int32)

In [15]:
A + B_tiled

array([[[ -5,  -5, -19,  -1,   6],
        [  8,  -2,  -9,  -2,   4],
        [ -6, -17,  -3, -18,  -4],
        [  4, -15,  -8,  -3,  11]],

       [[-10,  -1,   2,   4,   6],
        [  2,  -9,  -1,  -4,  -6],
        [  1, -15,  -1,  -3,  -6],
        [-12, -20,  11,   0,  -3]],

       [[-12,  -8, -15,  -9,  14],
        [  1,  -4,   0,  -2,  -3],
        [-16, -13, -13,  -7,   7],
        [  0, -14,   3,  -7,   3]]], dtype=int32)

In [17]:
np.all((A + B_tiled) == (A + B))

np.True_