### Array in n-th dimension

given array:
```python
array([[ -8,  -9, -10, -11],
       [ -4,  -5,  -6,  -7],
       [  0,  -1,  -2,  -3]])
```
first element in last dimension (1) will be `[-8, -9, -10, -11]` <br>
first element in last but one or first dimension (0) will be `[-8, -4, 0]` <br>

The question is, how do you iterate through i<sup>th</sup> dimension of an array ?

In [2]:
import numpy as np 

arr = np.array(
    [
        [ -8,  -9, -10, -11],
        [ -4,  -5,  -6,  -7],
        [  0,  -1,  -2,  -3]
    ]
)

# arr has 3 elements in axis=0 and 4 elements in axis=1
arr.shape

(3, 4)

In [10]:
def extract_axis(arr, axis):
    for i in range(arr.shape[axis]):
        slice_i = np.take(arr, i, axis=axis)
        print(f'axis={axis}, index={i}:')
        print(slice_i, '\n')

extract_axis(arr, 0)

axis=0, index=0:
[ -8  -9 -10 -11] 

axis=0, index=1:
[-4 -5 -6 -7] 

axis=0, index=2:
[ 0 -1 -2 -3] 



In [11]:
extract_axis(arr, 1)

axis=1, index=0:
[-8 -4  0] 

axis=1, index=1:
[-9 -5 -1] 

axis=1, index=2:
[-10  -6  -2] 

axis=1, index=3:
[-11  -7  -3] 



In [19]:
# for higher dimensions

arr = np.arange(3*4*5)
np.random.shuffle(arr)
arr = arr.reshape(3,4,5)

arr

array([[[33, 46, 34,  4,  6],
        [13, 32, 25, 51, 41],
        [17,  9, 10, 42, 30],
        [47, 52, 45, 36, 26]],

       [[18, 55, 58, 12, 19],
        [ 7, 57, 44,  3, 39],
        [53, 16, 15, 11, 31],
        [49, 54,  2, 37, 14]],

       [[ 8, 35, 50, 27,  5],
        [59, 21, 24, 23, 20],
        [ 0, 56, 40, 29, 48],
        [22, 28,  1, 43, 38]]])

In [20]:
extract_axis(arr, 0)

axis=0, index=0:
[[33 46 34  4  6]
 [13 32 25 51 41]
 [17  9 10 42 30]
 [47 52 45 36 26]] 

axis=0, index=1:
[[18 55 58 12 19]
 [ 7 57 44  3 39]
 [53 16 15 11 31]
 [49 54  2 37 14]] 

axis=0, index=2:
[[ 8 35 50 27  5]
 [59 21 24 23 20]
 [ 0 56 40 29 48]
 [22 28  1 43 38]] 



In [17]:
extract_axis(arr, 1)

axis=1, index=0:
[[55  8 14 58 26]
 [ 3 57 32 54 50]
 [ 1 10 53 31 44]] 

axis=1, index=1:
[[ 7 23 39 29 21]
 [45 43  6 49 33]
 [56 36 19 41 13]] 

axis=1, index=2:
[[ 5 12 16 47 48]
 [ 4 25 20 35 27]
 [34 52  9 42 40]] 

axis=1, index=3:
[[46 51 15 24 37]
 [28 17 59 22  0]
 [30 38 18 11  2]] 



In [18]:
extract_axis(arr, 2)

axis=2, index=0:
[[55  7  5 46]
 [ 3 45  4 28]
 [ 1 56 34 30]] 

axis=2, index=1:
[[ 8 23 12 51]
 [57 43 25 17]
 [10 36 52 38]] 

axis=2, index=2:
[[14 39 16 15]
 [32  6 20 59]
 [53 19  9 18]] 

axis=2, index=3:
[[58 29 47 24]
 [54 49 35 22]
 [31 41 42 11]] 

axis=2, index=4:
[[26 21 48 37]
 [50 33 27  0]
 [44 13 40  2]] 

