### Array in n-th dimension

given array:
```python
array([[ -8,  -9, -10, -11],
       [ -4,  -5,  -6,  -7],
       [  0,  -1,  -2,  -3]])
```
first element in last dimension (1) will be `[-8, -9, -10, -11]` <br>
first element in last but one or first dimension (0) will be `[-8, -4, 0]` <br>

The question is, how do you iterate through i<sup>th</sup> dimension of an array ?

In [1]:
import numpy as np 

arr = np.array(
    [
        [ -8,  -9, -10, -11],
        [ -4,  -5,  -6,  -7],
        [  0,  -1,  -2,  -3]
    ]
)

# arr has 3 elements in axis=0 and 4 elements in axis=1
arr.shape

(3, 4)

In [2]:
def extract_axis(arr, axis):
    for i in range(arr.shape[axis]):
        slice_i = np.take(arr, i, axis=axis)
        print(f'axis={axis}, index={i}:')
        print(slice_i, '\n')

extract_axis(arr, 0)

axis=0, index=0:
[ -8  -9 -10 -11] 

axis=0, index=1:
[-4 -5 -6 -7] 

axis=0, index=2:
[ 0 -1 -2 -3] 



In [3]:
extract_axis(arr, 1)

axis=1, index=0:
[-8 -4  0] 

axis=1, index=1:
[-9 -5 -1] 

axis=1, index=2:
[-10  -6  -2] 

axis=1, index=3:
[-11  -7  -3] 



In [4]:
# for higher dimensions

arr = np.random.randint(low=-10, high=10, size=(3, 4, 5))
arr

array([[[ -9,  -3, -10,   2,   8],
        [ -7,  -4,   6,  -7,   6],
        [-10,  -5,   2,   0,   9],
        [ -1,   3,   9,   1,   2]],

       [[  9,   9,  -1,   9,   7],
        [  2,   7,   2,   3,  -9],
        [  3,  -4,   1,   0,  -3],
        [  0,  -8, -10,   7,   6]],

       [[ -4,  -2,   8,  -9,   3],
        [ -6,   0, -10,   0,  -1],
        [ -5,   9,   2,   5,  -2],
        [ -9,   4,  -5,   2,  -3]]])

In [5]:
extract_axis(arr, 0)

axis=0, index=0:
[[ -9  -3 -10   2   8]
 [ -7  -4   6  -7   6]
 [-10  -5   2   0   9]
 [ -1   3   9   1   2]] 

axis=0, index=1:
[[  9   9  -1   9   7]
 [  2   7   2   3  -9]
 [  3  -4   1   0  -3]
 [  0  -8 -10   7   6]] 

axis=0, index=2:
[[ -4  -2   8  -9   3]
 [ -6   0 -10   0  -1]
 [ -5   9   2   5  -2]
 [ -9   4  -5   2  -3]] 



In [6]:
extract_axis(arr, 1)

axis=1, index=0:
[[ -9  -3 -10   2   8]
 [  9   9  -1   9   7]
 [ -4  -2   8  -9   3]] 

axis=1, index=1:
[[ -7  -4   6  -7   6]
 [  2   7   2   3  -9]
 [ -6   0 -10   0  -1]] 

axis=1, index=2:
[[-10  -5   2   0   9]
 [  3  -4   1   0  -3]
 [ -5   9   2   5  -2]] 

axis=1, index=3:
[[ -1   3   9   1   2]
 [  0  -8 -10   7   6]
 [ -9   4  -5   2  -3]] 



In [7]:
extract_axis(arr, 2)

axis=2, index=0:
[[ -9  -7 -10  -1]
 [  9   2   3   0]
 [ -4  -6  -5  -9]] 

axis=2, index=1:
[[-3 -4 -5  3]
 [ 9  7 -4 -8]
 [-2  0  9  4]] 

axis=2, index=2:
[[-10   6   2   9]
 [ -1   2   1 -10]
 [  8 -10   2  -5]] 

axis=2, index=3:
[[ 2 -7  0  1]
 [ 9  3  0  7]
 [-9  0  5  2]] 

axis=2, index=4:
[[ 8  6  9  2]
 [ 7 -9 -3  6]
 [ 3 -1 -2 -3]] 

