### Array in n-th dimension

given array:
```python
array([[ -8,  -9, -10, -11],
       [ -4,  -5,  -6,  -7],
       [  0,  -1,  -2,  -3]])
```
first element in last dimension (1) will be `[-8, -9, -10, -11]` <br>
first element in last but one or first dimension (0) will be `[-8, -4, 0]` <br>

The question is, how do you iterate through i<sup>th</sup> dimension of an array ?

In [1]:
import numpy as np 

arr = np.array(
    [
        [ -8,  -9, -10, -11],
        [ -4,  -5,  -6,  -7],
        [  0,  -1,  -2,  -3]
    ]
)

# arr has 3 elements in axis=0 and 4 elements in axis=1
arr.shape

(3, 4)

In [2]:
def extract_axis(arr, axis):
    for i in range(arr.shape[axis]):
        slice_i = np.take(arr, i, axis=axis)
        print(f'axis={axis}, index={i}:')
        print(slice_i, '\n')

extract_axis(arr, 0)

axis=0, index=0:
[ -8  -9 -10 -11] 

axis=0, index=1:
[-4 -5 -6 -7] 

axis=0, index=2:
[ 0 -1 -2 -3] 



In [3]:
extract_axis(arr, 1)

axis=1, index=0:
[-8 -4  0] 

axis=1, index=1:
[-9 -5 -1] 

axis=1, index=2:
[-10  -6  -2] 

axis=1, index=3:
[-11  -7  -3] 



In [15]:
# for higher dimensions

arr = np.array([[[f'a_{k}{j}{i}' for i in range(3)] for j in range(4)] for k in range(2)])
arr

array([[['a_000', 'a_001', 'a_002'],
        ['a_010', 'a_011', 'a_012'],
        ['a_020', 'a_021', 'a_022'],
        ['a_030', 'a_031', 'a_032']],

       [['a_100', 'a_101', 'a_102'],
        ['a_110', 'a_111', 'a_112'],
        ['a_120', 'a_121', 'a_122'],
        ['a_130', 'a_131', 'a_132']]], dtype='<U5')

In [16]:
extract_axis(arr, 0)

axis=0, index=0:
[['a_000' 'a_001' 'a_002']
 ['a_010' 'a_011' 'a_012']
 ['a_020' 'a_021' 'a_022']
 ['a_030' 'a_031' 'a_032']] 

axis=0, index=1:
[['a_100' 'a_101' 'a_102']
 ['a_110' 'a_111' 'a_112']
 ['a_120' 'a_121' 'a_122']
 ['a_130' 'a_131' 'a_132']] 



In [17]:
extract_axis(arr, 1)

axis=1, index=0:
[['a_000' 'a_001' 'a_002']
 ['a_100' 'a_101' 'a_102']] 

axis=1, index=1:
[['a_010' 'a_011' 'a_012']
 ['a_110' 'a_111' 'a_112']] 

axis=1, index=2:
[['a_020' 'a_021' 'a_022']
 ['a_120' 'a_121' 'a_122']] 

axis=1, index=3:
[['a_030' 'a_031' 'a_032']
 ['a_130' 'a_131' 'a_132']] 



In [18]:
extract_axis(arr, 2)

axis=2, index=0:
[['a_000' 'a_010' 'a_020' 'a_030']
 ['a_100' 'a_110' 'a_120' 'a_130']] 

axis=2, index=1:
[['a_001' 'a_011' 'a_021' 'a_031']
 ['a_101' 'a_111' 'a_121' 'a_131']] 

axis=2, index=2:
[['a_002' 'a_012' 'a_022' 'a_032']
 ['a_102' 'a_112' 'a_122' 'a_132']] 

